@Library('shared -lib')

pipeline {
    agent any
    stages{
        stage('git checkout'){
            steps{
            gitCheckout{
                branch:"main",
                url:"https://github.com/Harishbabumeesala/project1.git"
            }
            }
        }
    }
}
