pipeline {
    agent any
    stages{
        stage('git checkout'){
            steps{
                script{
                    git branch: 'main', url: 'https://github.com/Harishbabumeesala/project1.git'
                }
            }
        }
        stage("unit testing"){
            steps{
                sh 'mvn test'
            }
        }
    }
}
